services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/init://docker-entrypoint-initdb.d

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    volumes:
      - ./myapp:/app
